apiVersion: batch/v1
kind: Job
metadata:
  name: cupy-classification-job
  namespace: csuf-titans
spec:
  template:
    metadata:
      name: cupy-classification-job
    spec:
      containers:
        - name: cupy-classification-container
          image: rahulkrish28/cupy_classgpu:latest
          resources:
            requests:
              cpu: "4"
              memory: "8Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
              nvidia.com/gpu: 1
      restartPolicy: Never
  backoffLimit: 4
