apiVersion: batch/v1
kind: Job
metadata:
  name: pytorch-job
  namespace: csuf-titans
spec:
  template:
    metadata:
      name: pytorch-job
    spec:
      containers:
        - name: pytorch-container
          image: kirann9223/pytorch_gpu:latest
          resources:
            requests:
              cpu: "4"
              memory: "8Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
              nvidia.com/gpu: 1
      restartPolicy: Never
  backoffLimit: 4
