apiVersion: batch/v1
kind: Job
metadata:
  name: numba-clustering-job
  namespace: csuf-titans
spec:
  template:
    metadata:
      name: numba-clustering-job
    spec:
      containers:
        - name: numba-clustering-container
          image: kirann9223/numba-clustering-image:latest
          env:
            - name: NUMBA_CUDA_ARCH
              value: "84"
          resources:
            requests:
              cpu: "4"
              memory: "8Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
              nvidia.com/gpu: 1
      restartPolicy: Never
  backoffLimit: 4
